/**
 * Seed specifications for a realistic pilot dataset: an Israel-based staffing company placing
 * technical, security and medical personnel (many with military backgrounds) with employers in
 * Israel and Europe. Everything here is fed through the real service layer in ./index.ts so the
 * data passes the same validation, permission checks, audit logging and automations as the UI.
 *
 * Dates are relative to the seed run ("days from now"), so the pilot always looks current.
 */

export type UserKey = "noa" | "daniel" | "maya" | "yossi" | "lior" | "tamar" | "avi";
export type SourceKey = "website" | "idf_referral" | "linkedin" | "alljobs" | "partner_nordic" | "legacy_import" | "employee_referral" | "cyprus_jobs";
export type AccountKey = "nordsee" | "delta" | "cyprus_port" | "ial" | "helios" | "baltic" | "atlantic" | "bgaf";
export type CategoryKey = "welding" | "electrical" | "mechanical" | "security" | "logistics" | "medical" | "offshore" | "tech";

export type Proficiency = "basic" | "intermediate" | "advanced" | "expert";
export type LanguageLevel = "basic" | "conversational" | "professional" | "fluent" | "native";
export type WorkAuthType = "citizen" | "permanent_resident" | "work_permit" | "visa_sponsorship_required" | "none";
export type Rotation = "no_preference" | "short_rotation" | "long_rotation" | "fixed_term" | "permanent";
export type PayPeriod = "hourly" | "daily" | "weekly" | "monthly" | "annual";

export const USERS: { key: UserKey; name: string; email: string; role: "super_admin" | "standard" | "read_only"; status: "pending" | "active" | "deactivated"; canVerify: boolean; jobTitle: string; phone?: string }[] = [
  { key: "noa", name: "Noa Adler", email: "noa.adler@relaystaffing.example", role: "super_admin", status: "active", canVerify: true, jobTitle: "Head of Operations", phone: "+972 52 555 0101" },
  { key: "daniel", name: "Daniel Peretz", email: "daniel.peretz@relaystaffing.example", role: "standard", status: "active", canVerify: true, jobTitle: "Senior Recruiter & Evidence Reviewer", phone: "+972 54 555 0102" },
  { key: "maya", name: "Maya Cohen", email: "maya.cohen@relaystaffing.example", role: "standard", status: "active", canVerify: false, jobTitle: "Recruiter", phone: "+972 50 555 0103" },
  { key: "yossi", name: "Yossi Ben-David", email: "yossi.bendavid@relaystaffing.example", role: "standard", status: "active", canVerify: false, jobTitle: "Account Manager, Europe", phone: "+972 53 555 0104" },
  { key: "lior", name: "Lior Katz", email: "lior.katz@relaystaffing.example", role: "read_only", status: "active", canVerify: false, jobTitle: "Finance & Compliance" },
  { key: "tamar", name: "Tamar Levi", email: "tamar.levi@relaystaffing.example", role: "standard", status: "pending", canVerify: false, jobTitle: "Recruiter (starting)" },
  { key: "avi", name: "Avi Mizrahi", email: "avi.mizrahi@relaystaffing.example", role: "standard", status: "deactivated", canVerify: false, jobTitle: "Former recruiter" },
];

export const CATEGORIES: { key: CategoryKey; name: string; description: string; sortOrder: number }[] = [
  { key: "welding", name: "Welding & Fabrication", description: "Welding processes, pipefitting and drawing interpretation.", sortOrder: 10 },
  { key: "electrical", name: "Electrical & Instrumentation", description: "Industrial electrical work, control systems and renewables installation.", sortOrder: 20 },
  { key: "mechanical", name: "Mechanical & Heavy Equipment", description: "Mechanical maintenance and licensed plant / vehicle operation.", sortOrder: 30 },
  { key: "security", name: "Security & Protection", description: "Guarding, protection and surveillance competencies.", sortOrder: 40 },
  { key: "logistics", name: "Logistics & Operations", description: "Warehouse, fleet and dispatch coordination.", sortOrder: 50 },
  { key: "medical", name: "Medical, Health & Safety", description: "Clinical qualifications and safety training with expiry dates.", sortOrder: 60 },
  { key: "offshore", name: "Offshore & Energy Certifications", description: "Industry certificates required before mobilisation.", sortOrder: 70 },
  { key: "tech", name: "Technology & Communications", description: "Field technology, UAV and communications skills.", sortOrder: 80 },
];

export const SKILLS: { code: string; name: string; category: CategoryKey; synonyms: string[]; validityMonths?: number; owner?: UserKey; description?: string }[] = [
  { code: "weld.tig", name: "TIG welding (GTAW)", category: "welding", synonyms: ["tig", "gtaw", "argon welding", "ריתוך ארגון"], owner: "daniel" },
  { code: "weld.mig", name: "MIG/MAG welding (GMAW)", category: "welding", synonyms: ["mig", "mag", "gmaw", "co2 welding"], owner: "daniel" },
  { code: "weld.stick", name: "Stick welding (SMAW)", category: "welding", synonyms: ["smaw", "arc welding", "electrode welding", "stick"] },
  { code: "weld.pipe", name: "Pipe welding", category: "welding", synonyms: ["pipe welder", "pipeline welding", "6g"] },
  { code: "fab.blueprint", name: "Blueprint & isometric reading", category: "welding", synonyms: ["blueprint reading", "drawing interpretation", "isometrics"] },
  { code: "fab.pipefitting", name: "Pipefitting", category: "welding", synonyms: ["pipe fitter", "pipefitter"] },
  { code: "elec.industrial", name: "Industrial electrician", category: "electrical", synonyms: ["industrial electrical", "electrician", "חשמלאי", "electrical maintenance"], owner: "daniel" },
  { code: "elec.hv", name: "High-voltage systems", category: "electrical", synonyms: ["hv", "high voltage", "switchgear"] },
  { code: "instr.plc", name: "PLC programming & troubleshooting", category: "electrical", synonyms: ["plc", "siemens s7", "allen bradley", "automation"] },
  { code: "elec.solar", name: "PV / solar installation", category: "electrical", synonyms: ["solar", "photovoltaic", "pv installer"] },
  { code: "mech.hydraulics", name: "Hydraulic systems", category: "mechanical", synonyms: ["hydraulics", "hydraulic maintenance"] },
  { code: "mech.diesel", name: "Diesel engine maintenance", category: "mechanical", synonyms: ["diesel mechanic", "engine maintenance", "diesel"] },
  { code: "mech.hvac", name: "HVAC maintenance", category: "mechanical", synonyms: ["hvac", "air conditioning", "refrigeration"] },
  { code: "heavy.forklift", name: "Forklift licence", category: "mechanical", synonyms: ["forklift", "מלגזה", "reach truck"], validityMonths: 60 },
  { code: "heavy.crane", name: "Mobile crane operator licence", category: "mechanical", synonyms: ["crane operator", "crane licence", "מנופאי"], validityMonths: 24 },
  { code: "heavy.excavator", name: "Excavator / heavy plant operation", category: "mechanical", synonyms: ["excavator", "heavy equipment operator", "plant operator"] },
  { code: "sec.armed", name: "Armed security", category: "security", synonyms: ["armed guard", "armed security officer", "מאבטח חמוש"], owner: "yossi" },
  { code: "sec.cpo", name: "Close protection", category: "security", synonyms: ["cpo", "bodyguard", "close protection officer", "executive protection"] },
  { code: "sec.cctv", name: "CCTV & control room operation", category: "security", synonyms: ["cctv", "control room", "surveillance"] },
  { code: "sec.crowd", name: "Crowd & access management", category: "security", synonyms: ["crowd control", "access control", "event security"] },
  { code: "sec.firearms_instructor", name: "Firearms instructor certification", category: "security", synonyms: ["firearms instructor", "range instructor", "מדריך ירי"], validityMonths: 24 },
  { code: "log.warehouse", name: "Warehouse management", category: "logistics", synonyms: ["warehouse", "inventory", "wms", "מחסנאי"] },
  { code: "log.fleet", name: "Fleet coordination", category: "logistics", synonyms: ["fleet", "fleet management", "vehicle scheduling"] },
  { code: "log.dispatch", name: "Dispatch & routing", category: "logistics", synonyms: ["dispatch", "dispatcher", "routing"] },
  { code: "med.emt", name: "EMT certification", category: "medical", synonyms: ["emt", "emergency medical technician", "חובש"], validityMonths: 24 },
  { code: "med.paramedic", name: "Paramedic licence", category: "medical", synonyms: ["paramedic", "פראמדיק"], validityMonths: 24, owner: "daniel" },
  { code: "safety.first_aid", name: "First aid certificate", category: "medical", synonyms: ["first aid", "cpr", "עזרה ראשונה"], validityMonths: 24 },
  { code: "safety.wah", name: "Working at heights", category: "medical", synonyms: ["working at height", "wah", "rope access awareness", "עבודה בגובה"], validityMonths: 36 },
  { code: "safety.confined", name: "Confined space entry", category: "medical", synonyms: ["confined space", "confined spaces"], validityMonths: 36 },
  { code: "safety.h2s", name: "H2S awareness", category: "medical", synonyms: ["h2s", "hydrogen sulphide"], validityMonths: 24 },
  { code: "cert.bosiet", name: "BOSIET offshore survival", category: "offshore", synonyms: ["bosiet", "offshore survival", "opito", "huet"], validityMonths: 48, owner: "noa" },
  { code: "cert.gwo", name: "GWO Basic Safety Training", category: "offshore", synonyms: ["gwo", "gwo bst", "wind safety training"], validityMonths: 24 },
  { code: "cert.cdl", name: "Heavy truck licence (C/CE)", category: "offshore", synonyms: ["truck licence", "c licence", "ce licence", "hgv"], validityMonths: 60 },
  { code: "tech.drone", name: "UAV / drone operation", category: "tech", synonyms: ["drone", "uav", "rpas", "רחפן"], validityMonths: 24 },
  { code: "tech.network", name: "Network technician", category: "tech", synonyms: ["networking", "network installation", "structured cabling"] },
  { code: "tech.radio", name: "Radio & tactical communications", category: "tech", synonyms: ["radio operator", "communications", "קשר"] },
];

export const ROLE_FAMILIES: { code: string; name: string; description: string; weights: { skills: number; proficiency: number; experience: number; preferences: number; freshness: number } }[] = [
  { code: "industrial_trades", name: "Industrial trades", description: "Welders, fitters and mechanical technicians for shipyards, plants and construction.", weights: { skills: 0.45, proficiency: 0.2, experience: 0.15, preferences: 0.1, freshness: 0.1 } },
  { code: "electrical_field", name: "Electrical & field technicians", description: "Industrial electricians, PLC and renewables technicians including offshore rotations.", weights: { skills: 0.4, proficiency: 0.2, experience: 0.15, preferences: 0.15, freshness: 0.1 } },
  { code: "security_services", name: "Security & protection", description: "Armed and unarmed security, close protection and control-room roles.", weights: { skills: 0.35, proficiency: 0.15, experience: 0.25, preferences: 0.15, freshness: 0.1 } },
  { code: "logistics_ops", name: "Logistics & operations", description: "Warehouse, fleet and dispatch coordinators.", weights: { skills: 0.35, proficiency: 0.15, experience: 0.2, preferences: 0.2, freshness: 0.1 } },
  { code: "medical_safety", name: "Medical & safety", description: "Medics, paramedics and safety officers for remote and offshore sites.", weights: { skills: 0.4, proficiency: 0.2, experience: 0.15, preferences: 0.1, freshness: 0.15 } },
];

export const SOURCES: { key: SourceKey; name: string; type: "agency" | "referral" | "job_board" | "website" | "social" | "import" | "walk_in" | "partner" | "other"; contactName?: string; contactEmail?: string; commissionTerms?: string }[] = [
  { key: "website", name: "Company website — apply form", type: "website" },
  { key: "idf_referral", name: "Discharged soldiers programme referral", type: "referral", contactName: "Programme liaison office", commissionTerms: "No fee. Quarterly placement report shared with the programme." },
  { key: "linkedin", name: "LinkedIn", type: "social" },
  { key: "alljobs", name: "AllJobs board", type: "job_board" },
  { key: "partner_nordic", name: "Nordic Staffing Partners (agency)", type: "agency", contactName: "Ingrid Solberg", contactEmail: "ingrid@nordicstaffing.example", commissionTerms: "12% of first-year billing, payable after 90 days on assignment." },
  { key: "legacy_import", name: "Legacy Excel database", type: "import" },
  { key: "employee_referral", name: "Candidate / employee referral", type: "referral", commissionTerms: "ILS 1,500 referral bonus after placement completes probation." },
  { key: "cyprus_jobs", name: "Cyprus jobs board", type: "job_board" },
];

export const ACCOUNTS: {
  key: AccountKey;
  name: string;
  type: "employer" | "agency_partner" | "government" | "subcontractor" | "vendor" | "other";
  status: "prospect" | "active" | "inactive" | "blocked";
  industry: string;
  website?: string;
  country: string;
  city: string;
  owner: UserKey;
  currency: string;
  paymentTermsDays?: number;
  commercialTerms?: string;
  notes?: string;
  contacts: { first: string; last: string; email: string; phone?: string; title: string; isPrimary?: boolean; receivesShortlists?: boolean }[];
}[] = [
  {
    key: "nordsee",
    name: "Nordsee Werft GmbH",
    type: "employer",
    status: "active",
    industry: "Shipbuilding & repair",
    website: "https://nordsee-werft.example",
    country: "DE",
    city: "Hamburg",
    owner: "yossi",
    currency: "EUR",
    paymentTermsDays: 30,
    commercialTerms: "<p>Framework agreement signed March 2026. Hourly bill rates by trade; overtime above 40h/week at 125%. Accommodation provided by customer, travel reimbursed after 12 weeks. 30-day replacement guarantee.</p>",
    contacts: [
      { first: "Katrin", last: "Bauer", email: "k.bauer@nordsee-werft.example", phone: "+49 40 555 2001", title: "Head of Production", isPrimary: true, receivesShortlists: true },
      { first: "Jonas", last: "Richter", email: "j.richter@nordsee-werft.example", title: "HR Business Partner", receivesShortlists: true },
    ],
  },
  {
    key: "delta",
    name: "Delta Offshore Services B.V.",
    type: "employer",
    status: "active",
    industry: "Offshore maintenance",
    website: "https://delta-offshore.example",
    country: "NL",
    city: "Rotterdam",
    owner: "yossi",
    currency: "EUR",
    paymentTermsDays: 45,
    commercialTerms: "<p>Rotation 2 weeks on / 2 weeks off. Day rate includes offshore allowance. Customer requires <strong>verified</strong> BOSIET and work authorisation evidence before mobilisation; medicals arranged by customer.</p>",
    contacts: [
      { first: "Pieter", last: "de Vries", email: "p.devries@delta-offshore.example", phone: "+31 10 555 3001", title: "Operations Manager", isPrimary: true, receivesShortlists: true },
      { first: "Sanne", last: "Bakker", email: "s.bakker@delta-offshore.example", title: "Crew Coordinator", receivesShortlists: true },
    ],
  },
  {
    key: "cyprus_port",
    name: "Limassol Port Security Ltd",
    type: "employer",
    status: "active",
    industry: "Port & maritime security",
    country: "CY",
    city: "Limassol",
    owner: "yossi",
    currency: "EUR",
    paymentTermsDays: 30,
    commercialTerms: "<p>Monthly fee per officer. Customer sponsors work permits for non-EU officers; firearms licensing handled locally. Minimum 9-month commitment.</p>",
    contacts: [
      { first: "Andreas", last: "Christodoulou", email: "a.christodoulou@lps.example", phone: "+357 25 555 4001", title: "Security Director", isPrimary: true, receivesShortlists: true },
    ],
  },
  {
    key: "ial",
    name: "Israel Aerospace Logistics Ltd",
    type: "employer",
    status: "active",
    industry: "Aerospace logistics",
    country: "IL",
    city: "Lod",
    owner: "maya",
    currency: "ILS",
    paymentTermsDays: 60,
    commercialTerms: "<p>Monthly salary plus 18% service fee. Six-month probation, then direct-hire option with a conversion fee of one month's salary.</p>",
    contacts: [
      { first: "Ronit", last: "Shaked", email: "ronit.s@ial.example", phone: "+972 8 555 5001", title: "Logistics Manager", isPrimary: true, receivesShortlists: true },
      { first: "Uri", last: "Gold", email: "uri.g@ial.example", title: "HR Coordinator" },
    ],
  },
  {
    key: "helios",
    name: "Helios Solar Park S.A.",
    type: "employer",
    status: "prospect",
    industry: "Renewable energy",
    website: "https://helios-solar.example",
    country: "GR",
    city: "Thessaloniki",
    owner: "yossi",
    currency: "EUR",
    notes: "Met at Intersolar. Wants a crew of PV electricians for a 40 MW build starting Q4. Commercial terms not agreed yet.",
    contacts: [{ first: "Eleni", last: "Georgiou", email: "e.georgiou@helios-solar.example", title: "Project Director", isPrimary: true }],
  },
  {
    key: "baltic",
    name: "Baltic Windworks Sp. z o.o.",
    type: "employer",
    status: "active",
    industry: "Wind energy services",
    country: "PL",
    city: "Gdańsk",
    owner: "yossi",
    currency: "EUR",
    paymentTermsDays: 30,
    commercialTerms: "<p>Day rate per technician; GWO certificates must be valid for the full assignment. Customer provides PPE and site induction.</p>",
    contacts: [{ first: "Marek", last: "Kowalski", email: "m.kowalski@balticwind.example", phone: "+48 58 555 6001", title: "Site Manager", isPrimary: true, receivesShortlists: true }],
  },
  {
    key: "atlantic",
    name: "Atlantic Medical Staffing",
    type: "agency_partner",
    status: "inactive",
    industry: "Healthcare staffing",
    country: "IE",
    city: "Dublin",
    owner: "noa",
    currency: "EUR",
    notes: "Partner agency for Irish care roles. Paused in 2025 pending registration requirements.",
    contacts: [{ first: "Siobhan", last: "Murphy", email: "siobhan@atlanticmed.example", title: "Partnerships Lead", isPrimary: true }],
  },
  {
    key: "bgaf",
    name: "Ben Gurion Airport Facilities",
    type: "government",
    status: "prospect",
    industry: "Airport facilities",
    country: "IL",
    city: "Lod",
    owner: "maya",
    currency: "ILS",
    notes: "Tender-based. HVAC technician request withdrawn after budget cut; keep warm for 2027 tender.",
    contacts: [{ first: "Dov", last: "Harel", email: "dov.h@bgaf.example", title: "Facilities Procurement", isPrimary: true }],
  },
];

export type CandidateSpec = {
  key: string;
  first: string;
  last: string;
  email: string | null;
  phone: string | null;
  city: string;
  country: string;
  citizenships: string[];
  headline: string;
  summary?: string;
  military?: { role: string; unit?: string; rank?: string; startYearsAgo?: number; endYearsAgo?: number };
  years: number;
  relocate: boolean;
  preferredCountries?: string[];
  owner: UserKey;
  source: SourceKey;
  referrer?: string;
  commConsent: boolean;
  consentChannel?: "web_form" | "whatsapp" | "email" | "phone" | "paper" | "import";
  availableFromDays?: number;
  availableUntilDays?: number;
  minWeeks?: number;
  maxWeeks?: number;
  rotation?: Rotation;
  pay?: { amount: number; currency: string; period: PayPeriod };
  skills: { code: string; level: Proficiency; years?: number; wording?: string; review?: "verified" | "rejected" | "pending_review"; evidence?: string }[];
  languages: { code: string; level: LanguageLevel }[];
  workAuth: { country: string; type: WorkAuthType; validUntilDays?: number; verify?: boolean; notes?: string }[];
  shareWith?: AccountKey[];
  /** Customer sharing permission granted, then withdrawn (blocks disclosure). */
  withdrawShareWith?: AccountKey[];
  status?: "new" | "screening" | "active" | "placed" | "unavailable" | "withdrawn" | "archived";
  createdDaysAgo: number;
  /** Plain-text CV uploaded at intake; triggers the extraction job. */
  cvText?: string;
  forceCreate?: boolean;
  /** Candidate asked us to stop processing their profile this many days ago; makes the profile due for erasure. */
  withdrawProcessingDaysAgo?: number;
  /** Nothing has touched the profile since it was created (updated_at is backdated too), so it ages out. */
  dormant?: boolean;
  /** Documented reason to keep a due profile past the retention date. */
  retentionHold?: { reason: string; untilDays?: number };
};

export const CANDIDATES: CandidateSpec[] = [
  {
    key: "amir_levi",
    first: "Amir",
    last: "Levi",
    email: "amir.levi.weld@example.com",
    phone: "+972 52 410 7781",
    city: "Haifa",
    country: "IL",
    citizenships: ["IL"],
    headline: "TIG/MIG welder, 8 years in shipyard and pressure-vessel work",
    summary: "Trained as a combat engineer, then eight years at Israel Shipyards and a pressure-vessel fabricator. Comfortable with stainless and duplex, reads isometrics. Looking for a long European rotation.",
    military: { role: "Combat engineer", unit: "Engineering Corps, 601st Battalion", rank: "Staff Sergeant", startYearsAgo: 12, endYearsAgo: 9 },
    years: 8,
    relocate: true,
    preferredCountries: ["DE", "NL"],
    owner: "maya",
    source: "idf_referral",
    commConsent: true,
    consentChannel: "web_form",
    availableFromDays: -5,
    minWeeks: 26,
    maxWeeks: 52,
    rotation: "long_rotation",
    pay: { amount: 30, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.tig", level: "expert", years: 8, wording: "TIG stainless & duplex", review: "verified", evidence: "Practical test at Haifa training centre, 6G coupon passed 2026-05" },
      { code: "weld.mig", level: "advanced", years: 8, review: "verified", evidence: "Employer reference (Israel Shipyards) confirms 6 years MIG" },
      { code: "weld.pipe", level: "advanced", years: 5 },
      { code: "fab.blueprint", level: "intermediate", years: 6 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
      { code: "de", level: "basic" },
    ],
    workAuth: [
      { country: "IL", type: "citizen", verify: true },
      { country: "DE", type: "work_permit", validUntilDays: 400, verify: true, notes: "Skilled worker visa via Nordsee Werft framework" },
    ],
    shareWith: ["nordsee"],
    status: "active",
    createdDaysAgo: 48,
  },
  {
    key: "dmytro_bondar",
    first: "Dmytro",
    last: "Bondar",
    email: "d.bondar@example.com",
    phone: "+48 512 300 118",
    city: "Gdańsk",
    country: "PL",
    citizenships: ["UA"],
    headline: "Pipe welder (TIG/SMAW), 12 years across shipyards in Mykolaiv and Gdańsk",
    years: 12,
    relocate: true,
    preferredCountries: ["DE", "PL", "NL"],
    owner: "daniel",
    source: "partner_nordic",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: 7,
    minWeeks: 12,
    rotation: "long_rotation",
    pay: { amount: 32, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.tig", level: "expert", years: 12, review: "verified", evidence: "EN ISO 9606-1 certificate reviewed, valid to 2027-11" },
      { code: "weld.pipe", level: "expert", years: 10, review: "verified", evidence: "Certificate + Nordic Staffing reference" },
      { code: "weld.stick", level: "advanced", years: 12 },
      { code: "fab.pipefitting", level: "advanced", years: 8 },
    ],
    languages: [
      { code: "uk", level: "native" },
      { code: "pl", level: "professional" },
      { code: "en", level: "conversational" },
      { code: "de", level: "conversational" },
    ],
    workAuth: [
      { country: "PL", type: "permanent_resident", verify: true },
      { country: "DE", type: "work_permit", validUntilDays: 540, verify: false, notes: "Van der Elst permit application submitted; decision pending" },
    ],
    shareWith: ["nordsee"],
    status: "active",
    createdDaysAgo: 35,
  },
  {
    key: "yonatan_mizrahi",
    first: "Yonatan",
    last: "Mizrahi",
    email: "yonatan.m@example.com",
    phone: "+972 54 220 9931",
    city: "Ashdod",
    country: "IL",
    citizenships: ["IL"],
    headline: "Welder, 4 years structural steel",
    military: { role: "Infantry squad leader", unit: "Givati Brigade", rank: "Sergeant", startYearsAgo: 8, endYearsAgo: 5 },
    years: 4,
    relocate: true,
    owner: "maya",
    source: "website",
    commConsent: true,
    availableFromDays: 14,
    rotation: "no_preference",
    pay: { amount: 28, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.mig", level: "advanced", years: 4 },
      { code: "weld.tig", level: "advanced", years: 2, wording: "TIG - some experience on thin stainless" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "conversational" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    shareWith: ["nordsee"],
    status: "screening",
    createdDaysAgo: 9,
    cvText: `Yonatan Mizrahi
Ashdod, Israel | yonatan.m@example.com | +972 54 220 9931

Structural welder with 4 years of experience in steel fabrication. Israeli citizen.

EXPERIENCE
2022-2026  Welder, Ashdod Steel Works - MIG welding of structural steel, some TIG on thin stainless, blueprint reading.
2018-2021  Infantry squad leader, Givati Brigade (IDF).

SKILLS
MIG, TIG, arc welding, blueprint reading, forklift licence.

LANGUAGES
Hebrew (native), English (conversational).`,
  },
  {
    key: "sergei_volkov",
    first: "Sergei",
    last: "Volkov",
    email: "sergei.volkov@example.com",
    phone: "+972 50 818 4412",
    city: "Nof HaGalil",
    country: "IL",
    citizenships: ["IL", "RU"],
    headline: "Master welder, 15 years; completed Nordsee Werft spring refit",
    years: 15,
    relocate: true,
    preferredCountries: ["DE"],
    owner: "daniel",
    source: "alljobs",
    commConsent: true,
    consentChannel: "phone",
    availableFromDays: -10,
    minWeeks: 8,
    rotation: "fixed_term",
    pay: { amount: 36, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.tig", level: "expert", years: 15, review: "verified", evidence: "Nordsee Werft completion report and weld test log" },
      { code: "weld.stick", level: "expert", years: 15, review: "verified", evidence: "Nordsee Werft completion report" },
      { code: "weld.pipe", level: "advanced", years: 9 },
      { code: "fab.blueprint", level: "advanced", years: 12 },
    ],
    languages: [
      { code: "ru", level: "native" },
      { code: "he", level: "professional" },
      { code: "en", level: "basic" },
    ],
    workAuth: [
      { country: "IL", type: "citizen", verify: true },
      { country: "DE", type: "work_permit", validUntilDays: -30, verify: true, notes: "Permit from the spring campaign; renewal needed" },
    ],
    shareWith: ["nordsee"],
    status: "active",
    createdDaysAgo: 170,
  },
  {
    key: "tomer_azoulay",
    first: "Tomer",
    last: "Azoulay",
    email: "tomer.azoulay@example.com",
    phone: "+972 58 345 6620",
    city: "Beersheba",
    country: "IL",
    citizenships: ["IL", "FR"],
    headline: "Welder-mechanic, armoured vehicle maintenance background",
    military: { role: "Armored corps tank mechanic", unit: "7th Armored Brigade maintenance company", rank: "Sergeant First Class", startYearsAgo: 10, endYearsAgo: 6 },
    years: 6,
    relocate: true,
    preferredCountries: ["DE", "FR"],
    owner: "maya",
    source: "employee_referral",
    referrer: "Amir Levi",
    commConsent: true,
    consentChannel: "whatsapp",
    availableFromDays: 10,
    minWeeks: 20,
    rotation: "long_rotation",
    pay: { amount: 33, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.mig", level: "expert", years: 6, review: "verified", evidence: "Trade test at partner workshop, 2026-07" },
      { code: "weld.tig", level: "advanced", years: 4, review: "verified", evidence: "Trade test at partner workshop, 2026-07" },
      { code: "mech.hydraulics", level: "advanced", years: 6 },
      { code: "mech.diesel", level: "advanced", years: 6 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "fr", level: "fluent" },
      { code: "en", level: "professional" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "DE", type: "permanent_resident", verify: true, notes: "EU freedom of movement — French passport" },
    ],
    shareWith: ["nordsee"],
    status: "active",
    createdDaysAgo: 160,
  },
  {
    key: "noam_friedman",
    first: "Noam",
    last: "Friedman",
    email: "noam.friedman@example.com",
    phone: "+972 52 990 1140",
    city: "Tel Aviv",
    country: "IL",
    citizenships: ["IL"],
    headline: "Junior welder, navy engine-room technician",
    military: { role: "Navy engine room technician", unit: "Israeli Navy, missile boat flotilla", startYearsAgo: 6, endYearsAgo: 3 },
    years: 3,
    relocate: true,
    owner: "yossi",
    source: "website",
    commConsent: true,
    availableFromDays: 45,
    rotation: "short_rotation",
    pay: { amount: 26, currency: "EUR", period: "hourly" },
    skills: [
      { code: "weld.mig", level: "intermediate", years: 3 },
      { code: "weld.tig", level: "basic", years: 1 },
      { code: "mech.diesel", level: "intermediate", years: 3 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "active",
    createdDaysAgo: 21,
  },
  {
    key: "eitan_shapiro",
    first: "Eitan",
    last: "Shapiro",
    email: "eitan.shapiro@example.com",
    phone: "+972 54 771 2208",
    city: "Netanya",
    country: "IL",
    citizenships: ["IL", "NL"],
    headline: "Industrial electrician & PLC technician, offshore-ready (BOSIET)",
    summary: "Avionics technician in the air force, then nine years of industrial maintenance including two North Sea rotations. Dutch citizen through his mother.",
    military: { role: "Air force avionics technician", unit: "IAF Technical Division", rank: "Sergeant Major", startYearsAgo: 13, endYearsAgo: 9 },
    years: 9,
    relocate: true,
    preferredCountries: ["NL", "DE", "DK"],
    owner: "daniel",
    source: "linkedin",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: -3,
    minWeeks: 26,
    rotation: "long_rotation",
    pay: { amount: 40, currency: "EUR", period: "hourly" },
    skills: [
      { code: "elec.industrial", level: "expert", years: 9, review: "verified", evidence: "Dutch VCA-VOL and employer references reviewed" },
      { code: "instr.plc", level: "advanced", years: 6, review: "verified", evidence: "Siemens S7 certificate reviewed" },
      { code: "elec.hv", level: "intermediate", years: 3 },
      { code: "cert.bosiet", level: "advanced", review: "verified", evidence: "OPITO certificate 2025-03, valid 4 years" },
      { code: "safety.wah", level: "advanced", review: "verified", evidence: "GWO WAH module certificate 2025-03" },
      { code: "safety.confined", level: "intermediate" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
      { code: "nl", level: "conversational" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "NL", type: "citizen", verify: true, notes: "Dutch passport reviewed" },
    ],
    shareWith: ["delta", "nordsee"],
    status: "active",
    createdDaysAgo: 40,
  },
  {
    key: "omer_dahan",
    first: "Omer",
    last: "Dahan",
    email: "omer.dahan@example.com",
    phone: "+972 50 333 8071",
    city: "Rishon LeZion",
    country: "IL",
    citizenships: ["IL"],
    headline: "Industrial electrician, 7 years; BOSIET completed, certificate pending review",
    military: { role: "Combat engineer, heavy machinery operator", unit: "Engineering Corps", startYearsAgo: 11, endYearsAgo: 8 },
    years: 7,
    relocate: true,
    preferredCountries: ["NL"],
    owner: "maya",
    source: "idf_referral",
    commConsent: true,
    consentChannel: "whatsapp",
    availableFromDays: 14,
    minWeeks: 26,
    rotation: "long_rotation",
    pay: { amount: 35, currency: "EUR", period: "hourly" },
    skills: [
      { code: "elec.industrial", level: "advanced", years: 7, review: "verified", evidence: "Israeli electrician licence (Type 2) checked in registry" },
      { code: "instr.plc", level: "intermediate", years: 3 },
      { code: "cert.bosiet", level: "intermediate", review: "pending_review", evidence: "Scanned OPITO certificate uploaded; awaiting reviewer" },
      { code: "safety.wah", level: "intermediate" },
      { code: "heavy.excavator", level: "advanced", years: 3 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "NL", type: "work_permit", validUntilDays: 365, verify: false, notes: "Highly skilled migrant permit sponsored by Delta; awaiting IND decision" },
    ],
    shareWith: ["delta"],
    status: "active",
    createdDaysAgo: 30,
    cvText: `Omer Dahan
Rishon LeZion | omer.dahan@example.com | +972 50 333 8071

Industrial electrician with 7 years experience in factories and infrastructure projects. Israeli citizen.
Completed BOSIET offshore survival course (OPITO) in 2026. Working at height training completed.

EXPERIENCE
2019-2026  Electrician, Mekorot water infrastructure - industrial electrical maintenance, PLC troubleshooting (Siemens S7).
2015-2018  Combat engineer, heavy machinery operator, IDF Engineering Corps.

LANGUAGES: Hebrew (native), English (professional).`,
  },
  {
    key: "katarzyna_nowak",
    first: "Katarzyna",
    last: "Nowak",
    email: "k.nowak@example.com",
    phone: "+48 601 220 334",
    city: "Gdańsk",
    country: "PL",
    citizenships: ["PL"],
    headline: "Wind & industrial electrician, GWO certified, 10 years",
    years: 10,
    relocate: true,
    preferredCountries: ["PL", "DE", "DK"],
    owner: "yossi",
    source: "partner_nordic",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: 20,
    minWeeks: 12,
    rotation: "no_preference",
    pay: { amount: 30, currency: "EUR", period: "hourly" },
    skills: [
      { code: "elec.industrial", level: "expert", years: 10, review: "verified", evidence: "SEP E+D qualification certificate reviewed" },
      { code: "cert.gwo", level: "advanced", review: "verified", evidence: "GWO BST + WAH, WINDA record checked" },
      { code: "safety.wah", level: "advanced", review: "verified", evidence: "WINDA record" },
      { code: "elec.hv", level: "advanced", years: 6 },
      { code: "instr.plc", level: "advanced", years: 5 },
    ],
    languages: [
      { code: "pl", level: "native" },
      { code: "en", level: "professional" },
      { code: "de", level: "conversational" },
    ],
    workAuth: [
      { country: "PL", type: "citizen", verify: true },
      { country: "DE", type: "permanent_resident", verify: true, notes: "EU freedom of movement" },
    ],
    shareWith: ["baltic", "nordsee"],
    status: "active",
    createdDaysAgo: 26,
  },
  {
    key: "ruslan_koval",
    first: "Ruslan",
    last: "Koval",
    email: "ruslan.koval@example.com",
    phone: "+972 53 604 7719",
    city: "Haifa",
    country: "IL",
    citizenships: ["IL", "UA"],
    headline: "Electrician, PV installation lead, 5 years",
    military: { role: "Artillery fire-control technician", unit: "Artillery Corps", startYearsAgo: 9, endYearsAgo: 6 },
    years: 5,
    relocate: true,
    preferredCountries: ["GR", "CY", "DE"],
    owner: "daniel",
    source: "linkedin",
    commConsent: true,
    availableFromDays: 5,
    rotation: "fixed_term",
    pay: { amount: 27, currency: "EUR", period: "hourly" },
    skills: [
      { code: "elec.industrial", level: "advanced", years: 5, review: "verified", evidence: "Israeli electrician licence checked" },
      { code: "elec.solar", level: "advanced", years: 4, review: "verified", evidence: "Employer reference: 12 MW of utility-scale PV" },
      { code: "elec.hv", level: "basic", years: 1 },
    ],
    languages: [
      { code: "uk", level: "native" },
      { code: "ru", level: "fluent" },
      { code: "he", level: "professional" },
      { code: "en", level: "conversational" },
    ],
    workAuth: [{ country: "IL", type: "citizen", verify: true }],
    status: "active",
    createdDaysAgo: 18,
  },
  {
    key: "david_cohen",
    first: "David",
    last: "Cohen",
    email: "david.cohen88@example.com",
    phone: "+972 52 100 3390",
    city: "Jerusalem",
    country: "IL",
    citizenships: ["IL"],
    headline: "Apprentice electrician",
    military: { role: "Military police", unit: "Military Police Corps", startYearsAgo: 4, endYearsAgo: 1 },
    years: 2,
    relocate: false,
    owner: "yossi",
    source: "website",
    commConsent: false,
    availableFromDays: 0,
    skills: [{ code: "elec.industrial", level: "basic", years: 2 }],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "basic" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "new",
    createdDaysAgo: 6,
  },
  {
    key: "itai_ben_ami",
    first: "Itai",
    last: "Ben-Ami",
    email: "itai.benami@example.com",
    phone: "+972 54 508 1122",
    city: "Eilat",
    country: "IL",
    citizenships: ["IL"],
    headline: "Armed security team leader, firearms instructor",
    military: { role: "Infantry platoon sergeant", unit: "Golani Brigade, 13th Battalion", rank: "First Sergeant", startYearsAgo: 10, endYearsAgo: 6 },
    years: 6,
    relocate: true,
    preferredCountries: ["CY", "GR"],
    owner: "yossi",
    source: "idf_referral",
    commConsent: true,
    consentChannel: "whatsapp",
    availableFromDays: -2,
    minWeeks: 26,
    rotation: "short_rotation",
    pay: { amount: 2600, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "expert", years: 6, review: "verified", evidence: "Israeli firearms licence + employer reference (Eilat port)" },
      { code: "sec.crowd", level: "advanced", years: 6, review: "verified", evidence: "Employer reference" },
      { code: "sec.cctv", level: "intermediate", years: 3 },
      { code: "sec.firearms_instructor", level: "advanced", review: "verified", evidence: "Instructor certificate 2025-10" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
      { code: "ar", level: "conversational" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "CY", type: "work_permit", validUntilDays: 500, verify: true, notes: "Sponsored by Limassol Port Security" },
    ],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 15,
  },
  {
    key: "shira_katz",
    first: "Shira",
    last: "Katz",
    email: "shira.katz@example.com",
    phone: "+972 52 655 7810",
    city: "Herzliya",
    country: "IL",
    citizenships: ["IL"],
    headline: "Close protection & armed security officer, 5 years",
    military: { role: "Military police, close protection unit", unit: "Military Police Corps", rank: "Sergeant", startYearsAgo: 8, endYearsAgo: 5 },
    years: 5,
    relocate: true,
    preferredCountries: ["CY"],
    owner: "yossi",
    source: "linkedin",
    commConsent: true,
    availableFromDays: 0,
    minWeeks: 26,
    rotation: "fixed_term",
    pay: { amount: 2500, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "advanced", years: 5, review: "verified", evidence: "Licence and employer reference reviewed" },
      { code: "sec.cpo", level: "advanced", years: 4, review: "verified", evidence: "Close protection course certificate" },
      { code: "sec.cctv", level: "advanced", years: 3 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "CY", type: "work_permit", validUntilDays: 480, verify: true },
    ],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 14,
  },
  {
    key: "nikos_papadopoulos",
    first: "Nikos",
    last: "Papadopoulos",
    email: "nikos.p@example.com",
    phone: "+357 99 511 220",
    city: "Limassol",
    country: "CY",
    citizenships: ["CY", "GR"],
    headline: "Port security officer, CCTV supervisor, 8 years",
    military: { role: "Infantry (conscript service)", unit: "Hellenic Army", startYearsAgo: 11, endYearsAgo: 10 },
    years: 8,
    relocate: false,
    owner: "yossi",
    source: "cyprus_jobs",
    commConsent: true,
    consentChannel: "web_form",
    availableFromDays: -20,
    rotation: "permanent",
    pay: { amount: 2400, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "expert", years: 8, review: "verified", evidence: "Cyprus private guard licence verified" },
      { code: "sec.crowd", level: "advanced", years: 8 },
      { code: "sec.cctv", level: "expert", years: 6, review: "verified", evidence: "Employer reference" },
    ],
    languages: [
      { code: "el", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [{ country: "CY", type: "citizen", verify: true }],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 11,
  },
  {
    key: "alexey_petrov",
    first: "Alexey",
    last: "Petrov",
    email: "alexey.petrov@example.com",
    phone: "+972 58 771 0034",
    city: "Ashkelon",
    country: "IL",
    citizenships: ["IL", "RU"],
    headline: "Armed security officer, 4 years",
    military: { role: "Border police", unit: "Israel Border Police", startYearsAgo: 7, endYearsAgo: 4 },
    years: 4,
    relocate: true,
    owner: "maya",
    source: "alljobs",
    commConsent: true,
    availableFromDays: 3,
    rotation: "short_rotation",
    pay: { amount: 2700, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "advanced", years: 4, review: "pending_review", evidence: "Licence photo uploaded; needs reviewer check" },
      { code: "sec.cctv", level: "intermediate", years: 2 },
    ],
    languages: [
      { code: "ru", level: "native" },
      { code: "he", level: "fluent" },
      { code: "en", level: "conversational" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    shareWith: ["cyprus_port"],
    status: "screening",
    createdDaysAgo: 10,
  },
  {
    key: "gal_peretz",
    first: "Gal",
    last: "Peretz",
    email: "gal.peretz@example.com",
    phone: "+972 50 942 6675",
    city: "Petah Tikva",
    country: "IL",
    citizenships: ["IL"],
    headline: "Security officer and EMT, combat medic background",
    military: { role: "Infantry combat medic", unit: "Nahal Brigade", startYearsAgo: 6, endYearsAgo: 3 },
    years: 3,
    relocate: true,
    owner: "maya",
    source: "idf_referral",
    commConsent: true,
    consentChannel: "whatsapp",
    availableFromDays: 1,
    rotation: "fixed_term",
    pay: { amount: 2500, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "intermediate", years: 3, review: "verified", evidence: "Licence checked" },
      { code: "safety.first_aid", level: "expert", review: "verified", evidence: "MDA certificate" },
      { code: "med.emt", level: "advanced", review: "verified", evidence: "MDA EMT certificate valid to 2027" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "CY", type: "work_permit", validUntilDays: 420, verify: false, notes: "Permit issued; copy requested from candidate" },
    ],
    shareWith: ["cyprus_port"],
    status: "screening",
    createdDaysAgo: 8,
  },
  {
    key: "ronen_avraham",
    first: "Ronen",
    last: "Avraham",
    email: "ronen.avraham@example.com",
    phone: "+972 54 118 2290",
    city: "Bat Yam",
    country: "IL",
    citizenships: ["IL"],
    headline: "Security supervisor, 10 years",
    military: { role: "Logistics officer", unit: "Logistics Corps", rank: "Captain", startYearsAgo: 16, endYearsAgo: 11 },
    years: 10,
    relocate: true,
    owner: "yossi",
    source: "alljobs",
    commConsent: true,
    availableFromDays: 0,
    pay: { amount: 2800, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "expert", years: 10, review: "verified", evidence: "Licence checked" },
      { code: "sec.crowd", level: "expert", years: 10 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "CY", type: "work_permit", validUntilDays: 300, verify: true },
    ],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 12,
  },
  {
    key: "maria_ioannou",
    first: "Maria",
    last: "Ioannou",
    email: "maria.ioannou@example.com",
    phone: "+357 96 402 118",
    city: "Nicosia",
    country: "CY",
    citizenships: ["CY"],
    headline: "Security officer, retail and events, 6 years",
    years: 6,
    relocate: false,
    owner: "yossi",
    source: "cyprus_jobs",
    commConsent: true,
    availableFromDays: 0,
    pay: { amount: 2300, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "advanced", years: 4, review: "verified", evidence: "Cyprus guard licence" },
      { code: "sec.crowd", level: "advanced", years: 6 },
    ],
    languages: [
      { code: "el", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [{ country: "CY", type: "citizen", verify: true }],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 11,
  },
  {
    key: "yuval_stern",
    first: "Yuval",
    last: "Stern",
    email: "yuval.stern@example.com",
    phone: "+972 52 377 9018",
    city: "Modiin",
    country: "IL",
    citizenships: ["IL"],
    headline: "Close protection lead, special forces background",
    military: { role: "Special forces team leader", unit: "Maglan", rank: "Lieutenant", startYearsAgo: 11, endYearsAgo: 7 },
    years: 7,
    relocate: true,
    owner: "yossi",
    source: "employee_referral",
    referrer: "Itai Ben-Ami",
    commConsent: true,
    availableFromDays: 0,
    pay: { amount: 3200, currency: "EUR", period: "monthly" },
    skills: [
      { code: "sec.armed", level: "expert", years: 7, review: "verified", evidence: "Licence + references" },
      { code: "sec.cpo", level: "expert", years: 7, review: "verified", evidence: "Course certificate + references" },
      { code: "sec.firearms_instructor", level: "advanced", review: "verified", evidence: "Instructor certificate" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "CY", type: "work_permit", validUntilDays: 450, verify: true },
    ],
    shareWith: ["cyprus_port"],
    status: "active",
    createdDaysAgo: 13,
  },
  {
    key: "lior_biton",
    first: "Lior",
    last: "Biton",
    email: "lior.biton@example.com",
    phone: "+972 50 227 4481",
    city: "Lod",
    country: "IL",
    citizenships: ["IL"],
    headline: "Warehouse & fleet coordinator, ordnance logistics NCO",
    military: { role: "Logistics NCO", unit: "Ordnance Corps", rank: "Staff Sergeant", startYearsAgo: 9, endYearsAgo: 6 },
    years: 6,
    relocate: false,
    owner: "maya",
    source: "idf_referral",
    commConsent: true,
    availableFromDays: -60,
    rotation: "permanent",
    pay: { amount: 14000, currency: "ILS", period: "monthly" },
    skills: [
      { code: "log.warehouse", level: "expert", years: 6, review: "verified", evidence: "Employer reference (IAI supplier)" },
      { code: "heavy.forklift", level: "advanced", review: "verified", evidence: "Forklift licence valid to 2028" },
      { code: "log.fleet", level: "advanced", years: 4 },
      { code: "log.dispatch", level: "intermediate", years: 3 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
      { code: "ru", level: "basic" },
    ],
    workAuth: [{ country: "IL", type: "citizen", verify: true }],
    shareWith: ["ial"],
    status: "active",
    createdDaysAgo: 75,
  },
  {
    key: "adi_mor",
    first: "Adi",
    last: "Mor",
    email: "adi.mor@example.com",
    phone: "+972 54 630 5527",
    city: "Ramla",
    country: "IL",
    citizenships: ["IL"],
    headline: "Warehouse team lead, forklift licensed",
    military: { role: "Transport NCO", unit: "Logistics Corps", startYearsAgo: 7, endYearsAgo: 4 },
    years: 4,
    relocate: false,
    owner: "maya",
    source: "website",
    commConsent: true,
    availableFromDays: -30,
    rotation: "permanent",
    pay: { amount: 13000, currency: "ILS", period: "monthly" },
    skills: [
      { code: "log.warehouse", level: "advanced", years: 4 },
      { code: "heavy.forklift", level: "advanced", review: "verified", evidence: "Licence checked" },
      { code: "log.fleet", level: "intermediate", years: 2 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "conversational" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    shareWith: ["ial"],
    status: "active",
    createdDaysAgo: 68,
  },
  {
    key: "hanna_weiss",
    first: "Hanna",
    last: "Weiss",
    email: "hanna.weiss@example.com",
    phone: "+972 52 781 3349",
    city: "Haifa",
    country: "IL",
    citizenships: ["IL", "DE"],
    headline: "Logistics coordinator, air force supply background",
    military: { role: "Air force logistics", unit: "IAF Supply Wing", startYearsAgo: 6, endYearsAgo: 3 },
    years: 3,
    relocate: true,
    preferredCountries: ["DE"],
    owner: "yossi",
    source: "linkedin",
    commConsent: true,
    availableFromDays: 30,
    rotation: "permanent",
    pay: { amount: 13500, currency: "ILS", period: "monthly" },
    skills: [
      { code: "log.warehouse", level: "advanced", years: 3 },
      { code: "log.dispatch", level: "advanced", years: 3 },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "de", level: "fluent" },
      { code: "en", level: "professional" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "DE", type: "citizen" },
    ],
    status: "active",
    createdDaysAgo: 66,
  },
  {
    key: "daniel_rosen",
    first: "Daniel",
    last: "Rosen",
    email: "daniel.rosen@example.com",
    phone: "+972 54 992 0416",
    city: "Kfar Saba",
    country: "IL",
    citizenships: ["IL"],
    headline: "Paramedic, offshore-ready, 9 years pre-hospital care",
    military: { role: "Combat medic, paratroopers", unit: "Paratroopers Brigade", rank: "Sergeant First Class", startYearsAgo: 13, endYearsAgo: 9 },
    years: 9,
    relocate: true,
    preferredCountries: ["NL", "NO", "GB"],
    owner: "daniel",
    source: "linkedin",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: 10,
    minWeeks: 26,
    rotation: "long_rotation",
    pay: { amount: 4800, currency: "EUR", period: "monthly" },
    skills: [
      { code: "med.paramedic", level: "expert", years: 9, review: "verified", evidence: "MoH paramedic licence checked in registry" },
      { code: "med.emt", level: "expert", years: 9, review: "verified", evidence: "MDA certificate" },
      { code: "safety.first_aid", level: "expert" },
      { code: "cert.bosiet", level: "advanced", review: "verified", evidence: "OPITO BOSIET 2025-09" },
      { code: "safety.h2s", level: "intermediate" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "NL", type: "work_permit", validUntilDays: 600, verify: true, notes: "Highly skilled migrant permit via Delta" },
    ],
    shareWith: ["delta"],
    status: "active",
    createdDaysAgo: 9,
  },
  {
    key: "michal_oren",
    first: "Michal",
    last: "Oren",
    email: "michal.oren@example.com",
    phone: "+972 50 462 9903",
    city: "Haifa",
    country: "IL",
    citizenships: ["IL"],
    headline: "Paramedic, navy medic background, 6 years",
    military: { role: "Navy medic", unit: "Israeli Navy", startYearsAgo: 9, endYearsAgo: 6 },
    years: 6,
    relocate: true,
    owner: "daniel",
    source: "website",
    commConsent: true,
    availableFromDays: 5,
    rotation: "long_rotation",
    pay: { amount: 4500, currency: "EUR", period: "monthly" },
    skills: [
      { code: "med.paramedic", level: "advanced", years: 6, review: "verified", evidence: "MoH registry" },
      { code: "cert.bosiet", level: "intermediate" },
    ],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
    ],
    workAuth: [
      { country: "IL", type: "citizen" },
      { country: "NL", type: "work_permit", validUntilDays: 365, verify: false },
    ],
    shareWith: ["delta"],
    withdrawShareWith: ["delta"],
    status: "active",
    createdDaysAgo: 7,
  },
  {
    key: "piotr_zielinski",
    first: "Piotr",
    last: "Zieliński",
    email: "piotr.zielinski@example.com",
    phone: "+48 512 908 771",
    city: "Gdynia",
    country: "PL",
    citizenships: ["PL"],
    headline: "Wind turbine technician, GWO, 5 years",
    years: 5,
    relocate: true,
    preferredCountries: ["PL", "DE"],
    owner: "yossi",
    source: "partner_nordic",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: 15,
    rotation: "no_preference",
    pay: { amount: 28, currency: "EUR", period: "hourly" },
    skills: [
      { code: "cert.gwo", level: "advanced", review: "verified", evidence: "WINDA record; expires in ~3 months" },
      { code: "safety.wah", level: "advanced", review: "verified", evidence: "WINDA record" },
      { code: "elec.industrial", level: "advanced", years: 5, review: "verified", evidence: "SEP certificate" },
      { code: "mech.hydraulics", level: "intermediate", years: 3 },
    ],
    languages: [
      { code: "pl", level: "native" },
      { code: "en", level: "professional" },
    ],
    workAuth: [{ country: "PL", type: "citizen", verify: true }],
    shareWith: ["baltic"],
    status: "active",
    createdDaysAgo: 19,
  },
  {
    key: "ola_hansen",
    first: "Ola",
    last: "Hansen",
    email: "ola.hansen@example.com",
    phone: "+45 31 55 78 20",
    city: "Esbjerg",
    country: "DK",
    citizenships: ["DK"],
    headline: "Senior HV & wind technician, offshore, 11 years",
    years: 11,
    relocate: true,
    preferredCountries: ["DK", "DE", "NL", "PL"],
    owner: "yossi",
    source: "partner_nordic",
    commConsent: true,
    consentChannel: "email",
    availableFromDays: 25,
    rotation: "short_rotation",
    pay: { amount: 45, currency: "EUR", period: "hourly" },
    skills: [
      { code: "cert.gwo", level: "expert", review: "verified", evidence: "WINDA record" },
      { code: "safety.wah", level: "expert", review: "verified", evidence: "WINDA record" },
      { code: "elec.hv", level: "expert", years: 11, review: "verified", evidence: "Danish HV authorisation" },
      { code: "cert.bosiet", level: "advanced", review: "verified", evidence: "OPITO 2024-11" },
      { code: "elec.industrial", level: "expert", years: 11 },
    ],
    languages: [
      { code: "da", level: "native" },
      { code: "en", level: "fluent" },
      { code: "de", level: "professional" },
    ],
    workAuth: [
      { country: "DK", type: "citizen", verify: true },
      { country: "PL", type: "permanent_resident", notes: "EU freedom of movement" },
    ],
    shareWith: ["baltic"],
    status: "active",
    createdDaysAgo: 17,
  },
  {
    key: "eden_shalev",
    first: "Eden",
    last: "Shalev",
    email: "eden.shalev@example.com",
    phone: "+972 52 214 8890",
    city: "Holon",
    country: "IL",
    citizenships: ["IL"],
    headline: "Recently discharged, looking for a first technical role abroad",
    military: { role: "Infantry", unit: "Kfir Brigade", startYearsAgo: 3, endYearsAgo: 0 },
    years: 1,
    relocate: true,
    owner: "maya",
    source: "website",
    commConsent: true,
    availableFromDays: 0,
    skills: [],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "professional" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "new",
    createdDaysAgo: 0,
    cvText: `Eden Shalev
Holon, Israel | eden.shalev@example.com | +972 52 214 8890

Recently discharged infantry soldier (Kfir Brigade) with 1 year of experience as a warehouse assistant and forklift operator. Israeli citizen.
Completed a first aid course and a drone operator course during service. Interested in security or logistics roles abroad.

SKILLS: forklift, warehouse, first aid, drone, radio operator
LANGUAGES: Hebrew (native), English (professional)`,
  },
  {
    key: "amir_levy_dup",
    first: "Amir",
    last: "Levy",
    email: null,
    phone: "+972 52-410-7781",
    city: "Haifa",
    country: "IL",
    citizenships: ["IL"],
    headline: "Welder (walk-in registration at job fair)",
    years: 8,
    relocate: true,
    owner: "maya",
    source: "alljobs",
    commConsent: false,
    consentChannel: "paper",
    skills: [{ code: "weld.tig", level: "advanced" }],
    languages: [{ code: "he", level: "native" }],
    workAuth: [],
    status: "new",
    createdDaysAgo: 1,
    forceCreate: true,
  },
  {
    key: "boris_ivanov",
    first: "Boris",
    last: "Ivanov",
    email: "b.ivanov.weld@example.com",
    phone: "+972 54 771 0193",
    city: "Ashdod",
    country: "IL",
    citizenships: ["IL", "RU"],
    headline: "Pipe fitter, asked to be removed from the database",
    years: 12,
    relocate: false,
    owner: "daniel",
    source: "website",
    commConsent: true,
    consentChannel: "web_form",
    skills: [{ code: "weld.pipe", level: "advanced", years: 12 }],
    languages: [
      { code: "ru", level: "native" },
      { code: "he", level: "fluent" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "new",
    createdDaysAgo: 95,
    withdrawProcessingDaysAgo: 41,
  },
  {
    key: "yaakov_bergman",
    first: "Yaakov",
    last: "Bergman",
    email: "yaakov.bergman.sec@example.com",
    phone: "+972 50 662 3348",
    city: "Netanya",
    country: "IL",
    citizenships: ["IL"],
    headline: "Security supervisor (2024 Helios tender)",
    years: 9,
    relocate: true,
    owner: "yossi",
    source: "employee_referral",
    referrer: "Andreas Christodoulou",
    commConsent: false,
    consentChannel: "phone",
    skills: [{ code: "sec.armed", level: "expert", years: 9 }],
    languages: [
      { code: "he", level: "native" },
      { code: "en", level: "fluent" },
    ],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "archived",
    createdDaysAgo: 790,
    dormant: true,
    retentionHold: { reason: "Named in the Helios Solar tender dispute (2024 invoice). Legal asked us to keep the file until the case closes.", untilDays: 150 },
  },
  {
    key: "dana_klein",
    first: "Dana",
    last: "Klein",
    email: "dana.klein.log@example.com",
    phone: "+972 52 908 4471",
    city: "Rishon LeZion",
    country: "IL",
    citizenships: ["IL"],
    headline: "Logistics coordinator, registered during the 2024 job fair",
    years: 4,
    relocate: false,
    owner: "maya",
    source: "alljobs",
    commConsent: false,
    consentChannel: "paper",
    skills: [{ code: "log.warehouse", level: "intermediate", years: 4 }],
    languages: [{ code: "he", level: "native" }],
    workAuth: [{ country: "IL", type: "citizen" }],
    status: "archived",
    createdDaysAgo: 800,
    dormant: true,
  },
];

export type RequirementSpec = {
  kind: "mandatory" | "preferred";
  field: "skill" | "language" | "work_authorization" | "citizenship" | "availability_from" | "availability_duration_weeks" | "relocation" | "compensation_max" | "experience_years" | "military_role" | "certification" | "location_country";
  operator?: "equals" | "not_equals" | "gte" | "lte" | "in" | "not_in" | "contains" | "before" | "after" | "exists";
  value?: unknown;
  skill?: string;
  evidence?: "none" | "declared" | "verified";
  justification?: string;
  weight?: number;
};

export type RequisitionSpec = {
  key: string;
  account: AccountKey;
  contactIndex?: number;
  roleFamily: string;
  title: string;
  description: string;
  country: string;
  city: string;
  site?: string;
  startDays: number;
  durationWeeks: number;
  headcount: number;
  priority: "low" | "medium" | "high" | "urgent";
  owner: UserKey;
  bill?: { amount: number; currency: string; period: PayPeriod };
  pay?: { amount: number; currency: string; period: PayPeriod };
  requirements: RequirementSpec[];
  /** Final status after the seed's lifecycle steps. */
  finalStatus: "draft" | "open" | "on_hold" | "filled" | "closed" | "cancelled";
  closeReason?: string;
  createdDaysAgo: number;
  externalRef?: string;
};

export const REQUISITIONS: RequisitionSpec[] = [
  {
    key: "r0_spring_refit",
    account: "nordsee",
    roleFamily: "industrial_trades",
    title: "Hull welders — spring refit campaign",
    description: "<p>Two experienced hull welders for the spring dry-dock refit of two container feeders. Completed campaign; kept for history and reporting.</p>",
    country: "DE",
    city: "Hamburg",
    site: "Dock 11",
    startDays: -150,
    durationWeeks: 18,
    headcount: 2,
    priority: "medium",
    owner: "yossi",
    bill: { amount: 46, currency: "EUR", period: "hourly" },
    pay: { amount: 30, currency: "EUR", period: "hourly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "weld.tig", operator: "gte", value: "advanced", evidence: "verified", justification: "Customer weld procedure requires qualified TIG welders", weight: 2 },
      { kind: "mandatory", field: "work_authorization", justification: "Legal right to work in Germany" },
      { kind: "preferred", field: "skill", skill: "fab.blueprint", operator: "exists", weight: 1 },
    ],
    finalStatus: "closed",
    closeReason: "Campaign completed; both seats delivered on time",
    createdDaysAgo: 175,
    externalRef: "NW-2026-014",
  },
  {
    key: "r1_pipe_welders",
    account: "nordsee",
    contactIndex: 0,
    roleFamily: "industrial_trades",
    title: "Pipe welders (TIG) — Hamburg shipyard",
    description: "<p>Four TIG pipe welders for a 26-week newbuild outfitting phase. Stainless and duplex piping, 6G positions. Shift work, 40h/week plus overtime.</p><ul><li>Accommodation provided</li><li>Weld test on arrival</li></ul>",
    country: "DE",
    city: "Hamburg",
    site: "Hall 4 outfitting",
    startDays: 21,
    durationWeeks: 26,
    headcount: 4,
    priority: "high",
    owner: "yossi",
    bill: { amount: 48, currency: "EUR", period: "hourly" },
    pay: { amount: 31, currency: "EUR", period: "hourly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "weld.tig", operator: "gte", value: "advanced", evidence: "verified", justification: "Customer weld procedure specification requires certified TIG welders", weight: 2 },
      { kind: "mandatory", field: "work_authorization", evidence: "declared", justification: "Legal right to work in Germany before mobilisation" },
      { kind: "mandatory", field: "availability_from", justification: "Must be available for the outfitting phase start" },
      { kind: "mandatory", field: "availability_duration_weeks", value: 26, justification: "Full 26-week phase; partial assignments not accepted" },
      { kind: "preferred", field: "skill", skill: "weld.pipe", operator: "exists", weight: 2 },
      { kind: "preferred", field: "language", value: { language: "de", minProficiency: "conversational" }, weight: 1 },
      { kind: "preferred", field: "experience_years", operator: "gte", value: 5, weight: 1 },
      { kind: "preferred", field: "compensation_max", value: { amount: 34, currency: "EUR", period: "hourly" }, weight: 1 },
    ],
    finalStatus: "open",
    createdDaysAgo: 30,
    externalRef: "NW-2026-031",
  },
  {
    key: "r2_offshore_electricians",
    account: "delta",
    contactIndex: 0,
    roleFamily: "electrical_field",
    title: "Offshore maintenance electricians — North Sea rotation",
    description: "<p>Two industrial electricians for planned maintenance on gas platforms, 2/2 rotation for 12 months. Helicopter transfer from Den Helder.</p><p><strong>Mobilisation requires verified BOSIET and verified work authorisation.</strong></p>",
    country: "NL",
    city: "Den Helder",
    site: "L10 / K14 platforms",
    startDays: 35,
    durationWeeks: 52,
    headcount: 2,
    priority: "high",
    owner: "yossi",
    bill: { amount: 62, currency: "EUR", period: "hourly" },
    pay: { amount: 38, currency: "EUR", period: "hourly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "elec.industrial", operator: "gte", value: "advanced", evidence: "verified", justification: "Customer requires qualified industrial electricians for live systems", weight: 2 },
      { kind: "mandatory", field: "certification", skill: "cert.bosiet", operator: "exists", evidence: "verified", justification: "Offshore survival training is a legal mobilisation requirement", weight: 2 },
      { kind: "mandatory", field: "work_authorization", evidence: "verified", justification: "Dutch right-to-work evidence required by the customer's compliance team" },
      { kind: "mandatory", field: "relocation", value: true, justification: "Rotation requires travel to Den Helder" },
      { kind: "preferred", field: "skill", skill: "safety.wah", operator: "exists", weight: 1 },
      { kind: "preferred", field: "language", value: { language: "en", minProficiency: "professional" }, weight: 1 },
      { kind: "preferred", field: "experience_years", operator: "gte", value: 5, weight: 1 },
    ],
    finalStatus: "open",
    createdDaysAgo: 25,
    externalRef: "DOS-7781",
  },
  {
    key: "r3_port_security",
    account: "cyprus_port",
    contactIndex: 0,
    roleFamily: "security_services",
    title: "Armed port security officers — Limassol",
    description: "<p>Six armed security officers for the new container terminal. Twelve-hour shifts, 4 on / 4 off. Customer sponsors permits for non-EU officers and arranges local firearms licensing.</p>",
    country: "CY",
    city: "Limassol",
    site: "New container terminal",
    startDays: 14,
    durationWeeks: 39,
    headcount: 6,
    priority: "urgent",
    owner: "yossi",
    bill: { amount: 3400, currency: "EUR", period: "monthly" },
    pay: { amount: 2500, currency: "EUR", period: "monthly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "sec.armed", operator: "gte", value: "intermediate", evidence: "verified", justification: "Armed role: licence evidence must be reviewed before presentation", weight: 2 },
      { kind: "mandatory", field: "military_role", operator: "in", value: ["infantry", "combat", "military police", "border police", "special forces"], justification: "Customer tender requires prior armed service in a combat or policing role" },
      { kind: "mandatory", field: "language", value: { language: "en", minProficiency: "conversational" }, justification: "Terminal operations and incident reporting are in English" },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Cyprus (sponsored permit acceptable)" },
      { kind: "preferred", field: "skill", skill: "sec.cctv", operator: "exists", weight: 1 },
      { kind: "preferred", field: "skill", skill: "sec.crowd", operator: "exists", weight: 1 },
      { kind: "preferred", field: "experience_years", operator: "gte", value: 3, weight: 1 },
      { kind: "preferred", field: "compensation_max", value: { amount: 2600, currency: "EUR", period: "monthly" }, weight: 1 },
    ],
    finalStatus: "open",
    createdDaysAgo: 12,
    externalRef: "LPS-T-2026-03",
  },
  {
    key: "r4_warehouse_coordinator",
    account: "ial",
    contactIndex: 0,
    roleFamily: "logistics_ops",
    title: "Warehouse & fleet coordinator — Lod",
    description: "<p>Coordinator for the spare-parts warehouse and a fleet of 14 delivery vehicles. Full-time, on-site, six-month probation.</p>",
    country: "IL",
    city: "Lod",
    startDays: -40,
    durationWeeks: 52,
    headcount: 1,
    priority: "medium",
    owner: "maya",
    bill: { amount: 21000, currency: "ILS", period: "monthly" },
    pay: { amount: 14500, currency: "ILS", period: "monthly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "log.warehouse", operator: "gte", value: "advanced", justification: "Runs the warehouse independently from day one", weight: 2 },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Israel" },
      { kind: "mandatory", field: "language", value: { language: "he", minProficiency: "professional" }, justification: "Safety briefings and systems are in Hebrew" },
      { kind: "preferred", field: "skill", skill: "heavy.forklift", operator: "exists", evidence: "verified", weight: 1 },
      { kind: "preferred", field: "skill", skill: "log.fleet", operator: "exists", weight: 1 },
    ],
    finalStatus: "filled",
    createdDaysAgo: 70,
    externalRef: "IAL-LOG-22",
  },
  {
    key: "r5_pv_electricians",
    account: "helios",
    contactIndex: 0,
    roleFamily: "electrical_field",
    title: "PV installation electricians — Thessaloniki",
    description: "<p>Draft: crew of five PV electricians for a 40 MW ground-mount build. Commercial terms not yet agreed; do not open until the framework is signed.</p>",
    country: "GR",
    city: "Thessaloniki",
    startDays: 60,
    durationWeeks: 20,
    headcount: 5,
    priority: "medium",
    owner: "yossi",
    requirements: [
      { kind: "mandatory", field: "skill", skill: "elec.solar", operator: "gte", value: "intermediate", justification: "Utility-scale PV installation experience required" },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Greece" },
      { kind: "preferred", field: "skill", skill: "elec.hv", operator: "exists", weight: 1 },
    ],
    finalStatus: "draft",
    createdDaysAgo: 3,
  },
  {
    key: "r6_wind_technicians",
    account: "baltic",
    contactIndex: 0,
    roleFamily: "electrical_field",
    title: "GWO wind turbine technicians — Gdańsk",
    description: "<p>Three GWO-certified technicians for onshore turbine commissioning. On hold: customer awaiting turbine delivery date.</p>",
    country: "PL",
    city: "Gdańsk",
    startDays: 45,
    durationWeeks: 16,
    headcount: 3,
    priority: "medium",
    owner: "yossi",
    bill: { amount: 52, currency: "EUR", period: "hourly" },
    pay: { amount: 33, currency: "EUR", period: "hourly" },
    requirements: [
      { kind: "mandatory", field: "certification", skill: "cert.gwo", operator: "exists", evidence: "verified", justification: "GWO BST is mandatory for site access", weight: 2 },
      { kind: "mandatory", field: "skill", skill: "safety.wah", operator: "exists", evidence: "verified", justification: "Working at heights certificate required for site access" },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Poland" },
      { kind: "preferred", field: "skill", skill: "elec.hv", operator: "exists", weight: 1 },
      { kind: "preferred", field: "language", value: { language: "en", minProficiency: "professional" }, weight: 1 },
    ],
    finalStatus: "on_hold",
    createdDaysAgo: 20,
    externalRef: "BW-COM-09",
  },
  {
    key: "r7_plc_electricians",
    account: "nordsee",
    contactIndex: 1,
    roleFamily: "electrical_field",
    title: "Industrial electricians (PLC) — Hamburg",
    description: "<p>Two electricians with PLC troubleshooting experience for crane and conveyor systems in the yard. 20 weeks.</p>",
    country: "DE",
    city: "Hamburg",
    startDays: 28,
    durationWeeks: 20,
    headcount: 2,
    priority: "medium",
    owner: "yossi",
    bill: { amount: 50, currency: "EUR", period: "hourly" },
    pay: { amount: 32, currency: "EUR", period: "hourly" },
    requirements: [
      { kind: "mandatory", field: "skill", skill: "elec.industrial", operator: "gte", value: "advanced", evidence: "verified", justification: "Qualified electrician required for yard systems", weight: 2 },
      { kind: "mandatory", field: "skill", skill: "instr.plc", operator: "gte", value: "intermediate", justification: "Role is primarily PLC fault-finding" },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Germany" },
      { kind: "preferred", field: "language", value: { language: "de", minProficiency: "conversational" }, weight: 1 },
    ],
    finalStatus: "open",
    createdDaysAgo: 22,
    externalRef: "NW-2026-033",
  },
  {
    key: "r8_hvac",
    account: "bgaf",
    contactIndex: 0,
    roleFamily: "industrial_trades",
    title: "Facilities HVAC technicians",
    description: "<p>Cancelled: customer withdrew the budget after the tender review.</p>",
    country: "IL",
    city: "Lod",
    startDays: 10,
    durationWeeks: 52,
    headcount: 3,
    priority: "low",
    owner: "maya",
    requirements: [
      { kind: "mandatory", field: "skill", skill: "mech.hvac", operator: "gte", value: "intermediate", justification: "Core competency for the role" },
      { kind: "mandatory", field: "work_authorization", justification: "Right to work in Israel" },
    ],
    finalStatus: "cancelled",
    closeReason: "Budget withdrawn by customer after tender review",
    createdDaysAgo: 40,
  },
  {
    key: "r9_offshore_medic",
    account: "delta",
    contactIndex: 1,
    roleFamily: "medical_safety",
    title: "Offshore medic (paramedic) — rotation",
    description: "<p>One paramedic for the K14 platform, 2/2 rotation. Verified paramedic licence and BOSIET required before mobilisation.</p>",
    country: "NL",
    city: "Den Helder",
    site: "K14 platform",
    startDays: 40,
    durationWeeks: 52,
    headcount: 1,
    priority: "high",
    owner: "yossi",
    bill: { amount: 7200, currency: "EUR", period: "monthly" },
    pay: { amount: 4900, currency: "EUR", period: "monthly" },
    requirements: [
      { kind: "mandatory", field: "certification", skill: "med.paramedic", operator: "exists", evidence: "verified", justification: "Licensed paramedic required by offshore medical regulations", weight: 2 },
      { kind: "mandatory", field: "certification", skill: "cert.bosiet", operator: "exists", evidence: "verified", justification: "Offshore survival training is a legal mobilisation requirement" },
      { kind: "mandatory", field: "work_authorization", evidence: "verified", justification: "Dutch right-to-work evidence required by the customer" },
      { kind: "mandatory", field: "language", value: { language: "en", minProficiency: "professional" }, justification: "Medical reporting in English" },
      { kind: "preferred", field: "skill", skill: "safety.h2s", operator: "exists", weight: 1 },
    ],
    finalStatus: "open",
    createdDaysAgo: 10,
    externalRef: "DOS-7802",
  },
];

export type StagePath = "sourced" | "contacted" | "interested" | "screening" | "interviewing" | "presented" | "customer_review" | "offered" | "accepted" | "placed_active" | "placed_completed" | "declined_by_candidate" | "rejected_by_customer" | "withdrawn" | "not_eligible";

export type SubmissionSpec = {
  candidate: string;
  requisition: string;
  path: StagePath;
  /** For closing stages. */
  reason?: "compensation_mismatch" | "availability_conflict" | "location_mismatch" | "missing_evidence" | "failed_interview" | "customer_preference" | "candidate_withdrew" | "duplicate" | "seat_unavailable" | "other";
  /** Stage the submission reached before closing (for declined/rejected/withdrawn paths). */
  closeFrom?: "sourced" | "contacted" | "interested" | "screening" | "interviewing" | "presented" | "customer_review" | "offered";
  notes?: string;
  overrideReview?: string;
  interviews?: { type: "screening_call" | "technical" | "customer_interview" | "ai_chat_screening" | "reference_check"; inDays: number; outcome?: "pass" | "fail" | "hold"; summary?: string; withContact?: boolean }[];
  disclose?: boolean;
  plannedStartDays?: number;
  actualStartDays?: number;
  actualEndDays?: number;
  createdDaysAgo: number;
  stageChangedDaysAgo: number;
  outreach?: string;
};

export const SUBMISSIONS: SubmissionSpec[] = [
  // Completed spring campaign (history)
  { candidate: "sergei_volkov", requisition: "r0_spring_refit", path: "placed_completed", interviews: [{ type: "screening_call", inDays: -168, outcome: "pass", summary: "Strong TIG background, available immediately." }], disclose: true, plannedStartDays: -150, actualStartDays: -150, actualEndDays: -24, createdDaysAgo: 172, stageChangedDaysAgo: 24 },
  { candidate: "tomer_azoulay", requisition: "r0_spring_refit", path: "placed_completed", interviews: [{ type: "screening_call", inDays: -166, outcome: "pass" }], disclose: true, plannedStartDays: -150, actualStartDays: -148, actualEndDays: -24, createdDaysAgo: 170, stageChangedDaysAgo: 24 },

  // R1 pipe welders — 4 seats
  { candidate: "dmytro_bondar", requisition: "r1_pipe_welders", path: "accepted", interviews: [{ type: "screening_call", inDays: -20, outcome: "pass", summary: "12 years pipe welding, certificates current." }, { type: "customer_interview", inDays: -9, outcome: "pass", withContact: true, summary: "Katrin Bauer: strong fit, start as soon as permit confirmed." }], disclose: true, plannedStartDays: 21, createdDaysAgo: 28, stageChangedDaysAgo: 3, outreach: "Interest check" },
  { candidate: "amir_levi", requisition: "r1_pipe_welders", path: "offered", interviews: [{ type: "screening_call", inDays: -18, outcome: "pass" }, { type: "customer_interview", inDays: -6, outcome: "pass", withContact: true, summary: "Customer impressed with duplex experience." }], disclose: true, createdDaysAgo: 27, stageChangedDaysAgo: 2, outreach: "Interest check" },
  { candidate: "tomer_azoulay", requisition: "r1_pipe_welders", path: "customer_review", interviews: [{ type: "screening_call", inDays: -12, outcome: "pass", summary: "Returning candidate from the spring campaign." }], disclose: true, createdDaysAgo: 20, stageChangedDaysAgo: 4 },
  { candidate: "yonatan_mizrahi", requisition: "r1_pipe_welders", path: "screening", notes: "TIG proficiency claimed at advanced level; trade test required before presentation.", createdDaysAgo: 8, stageChangedDaysAgo: 6 },
  { candidate: "sergei_volkov", requisition: "r1_pipe_welders", path: "contacted", notes: "Left voicemail; German permit expired and needs renewal.", createdDaysAgo: 9, stageChangedDaysAgo: 7, outreach: "Availability reconfirmation" },
  { candidate: "noam_friedman", requisition: "r1_pipe_welders", path: "not_eligible", reason: "availability_conflict", notes: "Available only from mid-November; outfitting starts earlier.", createdDaysAgo: 15, stageChangedDaysAgo: 14 },

  // R2 offshore electricians — 2 seats
  { candidate: "eitan_shapiro", requisition: "r2_offshore_electricians", path: "accepted", interviews: [{ type: "technical", inDays: -14, outcome: "pass", summary: "PLC and HV knowledge confirmed by Delta's lead engineer." }, { type: "customer_interview", inDays: -7, outcome: "pass", withContact: true }], disclose: true, plannedStartDays: 35, createdDaysAgo: 22, stageChangedDaysAgo: 2 },
  { candidate: "omer_dahan", requisition: "r2_offshore_electricians", path: "interviewing", interviews: [{ type: "screening_call", inDays: -5, outcome: "pass", summary: "Motivated; BOSIET certificate uploaded, awaiting reviewer." }, { type: "technical", inDays: 2, withContact: false }], createdDaysAgo: 16, stageChangedDaysAgo: 5, outreach: "Interview confirmation" },
  { candidate: "ola_hansen", requisition: "r2_offshore_electricians", path: "sourced", notes: "Nordic Staffing suggested him for the second seat; NL right-to-work not yet recorded.", createdDaysAgo: 4, stageChangedDaysAgo: 4 },
  { candidate: "david_cohen", requisition: "r2_offshore_electricians", path: "not_eligible", reason: "missing_evidence", notes: "Apprentice level; no BOSIET.", createdDaysAgo: 5, stageChangedDaysAgo: 5 },

  // R3 port security — 6 seats
  { candidate: "shira_katz", requisition: "r3_port_security", path: "accepted", interviews: [{ type: "screening_call", inDays: -9, outcome: "pass" }, { type: "customer_interview", inDays: -4, outcome: "pass", withContact: true, summary: "Andreas: approve; permit already issued." }], disclose: true, plannedStartDays: 14, createdDaysAgo: 11, stageChangedDaysAgo: 1 },
  { candidate: "nikos_papadopoulos", requisition: "r3_port_security", path: "accepted", interviews: [{ type: "customer_interview", inDays: -3, outcome: "pass", withContact: true }], disclose: true, plannedStartDays: 14, createdDaysAgo: 10, stageChangedDaysAgo: 1 },
  { candidate: "itai_ben_ami", requisition: "r3_port_security", path: "offered", interviews: [{ type: "screening_call", inDays: -10, outcome: "pass" }, { type: "customer_interview", inDays: -3, outcome: "pass", withContact: true, summary: "Customer wants him as shift lead." }], disclose: true, createdDaysAgo: 11, stageChangedDaysAgo: 1, outreach: "Interest check" },
  { candidate: "alexey_petrov", requisition: "r3_port_security", path: "interviewing", interviews: [{ type: "screening_call", inDays: -4, outcome: "pass" }, { type: "customer_interview", inDays: 3, withContact: true }], createdDaysAgo: 9, stageChangedDaysAgo: 4 },
  { candidate: "gal_peretz", requisition: "r3_port_security", path: "interviewing", interviews: [{ type: "screening_call", inDays: 1 }], createdDaysAgo: 7, stageChangedDaysAgo: 2, outreach: "Interview confirmation" },
  { candidate: "maria_ioannou", requisition: "r3_port_security", path: "declined_by_candidate", reason: "compensation_mismatch", closeFrom: "offered", overrideReview: "Civilian security background accepted by the customer in writing (no military service requirement for EU nationals).", interviews: [{ type: "customer_interview", inDays: -5, outcome: "pass", withContact: true }], disclose: true, notes: "Declined: current employer matched the offer.", createdDaysAgo: 10, stageChangedDaysAgo: 1 },
  { candidate: "yuval_stern", requisition: "r3_port_security", path: "rejected_by_customer", reason: "customer_preference", closeFrom: "customer_review", interviews: [{ type: "screening_call", inDays: -8, outcome: "pass" }], disclose: true, notes: "Customer preferred candidates willing to commit beyond 9 months.", createdDaysAgo: 11, stageChangedDaysAgo: 2 },
  { candidate: "ronen_avraham", requisition: "r3_port_security", path: "not_eligible", reason: "other", notes: "Military role (logistics officer) outside the customer's tender requirement.", createdDaysAgo: 10, stageChangedDaysAgo: 9 },

  // R4 warehouse coordinator — 1 seat, filled
  { candidate: "adi_mor", requisition: "r4_warehouse_coordinator", path: "customer_review", interviews: [{ type: "screening_call", inDays: -55, outcome: "pass" }], disclose: true, notes: "Backup candidate; customer chose Lior Biton. Kept warm for the second warehouse.", createdDaysAgo: 60, stageChangedDaysAgo: 44 },
  { candidate: "lior_biton", requisition: "r4_warehouse_coordinator", path: "placed_active", interviews: [{ type: "screening_call", inDays: -62, outcome: "pass" }, { type: "customer_interview", inDays: -50, outcome: "pass", withContact: true, summary: "Ronit: hire." }], disclose: true, plannedStartDays: -40, actualStartDays: -40, createdDaysAgo: 65, stageChangedDaysAgo: 40 },
  { candidate: "hanna_weiss", requisition: "r4_warehouse_coordinator", path: "declined_by_candidate", reason: "availability_conflict", closeFrom: "interested", notes: "Relocating to Germany; not available for a Lod-based role.", createdDaysAgo: 58, stageChangedDaysAgo: 52 },

  // R6 wind technicians — on hold
  { candidate: "katarzyna_nowak", requisition: "r6_wind_technicians", path: "interested", createdDaysAgo: 18, stageChangedDaysAgo: 16 },
  { candidate: "piotr_zielinski", requisition: "r6_wind_technicians", path: "screening", notes: "GWO expires in ~3 months; refresher must be booked before mobilisation.", createdDaysAgo: 17, stageChangedDaysAgo: 15 },
  { candidate: "ola_hansen", requisition: "r6_wind_technicians", path: "interested", createdDaysAgo: 15, stageChangedDaysAgo: 14 },

  // R7 PLC electricians — stalled (no new submissions for a while)
  { candidate: "katarzyna_nowak", requisition: "r7_plc_electricians", path: "screening", createdDaysAgo: 20, stageChangedDaysAgo: 12 },
  { candidate: "eitan_shapiro", requisition: "r7_plc_electricians", path: "sourced", notes: "Only if the Delta offer falls through.", createdDaysAgo: 19, stageChangedDaysAgo: 19 },
  { candidate: "ruslan_koval", requisition: "r7_plc_electricians", path: "sourced", createdDaysAgo: 18, stageChangedDaysAgo: 18 },

  // R9 offshore medic — 1 seat
  { candidate: "daniel_rosen", requisition: "r9_offshore_medic", path: "presented", interviews: [{ type: "screening_call", inDays: -6, outcome: "pass", summary: "Licence, BOSIET and permit all verified." }], disclose: true, createdDaysAgo: 8, stageChangedDaysAgo: 2 },
  { candidate: "michal_oren", requisition: "r9_offshore_medic", path: "interested", notes: "Withdrew permission to be shared with Delta on a call; do not disclose until re-granted.", createdDaysAgo: 6, stageChangedDaysAgo: 3 },
];

export const TEMPLATES: { name: string; channel: "whatsapp" | "email" | "sms" | "manual"; language?: string; providerTemplateId?: string; subject?: string; body: string; status: "draft" | "approved" | "rejected"; category: string }[] = [
  {
    name: "Interest check",
    channel: "whatsapp",
    providerTemplateId: "interest_check_v2",
    body: "Hi {{first_name}}, this is {{recruiter_name}} from Relay Staffing. We have a {{role_title}} role in {{location}} starting {{start_date}}. Are you interested and still available? Reply YES or NO.",
    status: "approved",
    category: "outreach",
  },
  {
    name: "Interest check",
    channel: "email",
    subject: "{{role_title}} in {{location}} — are you interested?",
    body: "Hi {{first_name}},\n\nWe are shortlisting for a {{role_title}} position in {{location}}, starting {{start_date}}. Based on your profile you could be a strong fit.\n\nCould you reply to confirm whether you are interested and still available from that date?\n\nBest regards,\n{{recruiter_name}}\nRelay Staffing",
    status: "approved",
    category: "outreach",
  },
  {
    name: "Availability reconfirmation",
    channel: "whatsapp",
    providerTemplateId: "availability_reconfirm_v1",
    body: "Hi {{first_name}}, {{recruiter_name}} from Relay Staffing here. Are you still available for assignments from {{start_date}}? Reply with the earliest date you can start.",
    status: "approved",
    category: "availability",
  },
  {
    name: "Availability reconfirmation",
    channel: "email",
    subject: "Quick check: are you still available?",
    body: "Hi {{first_name}},\n\nTo keep your profile current, could you confirm the earliest date you are available for a new assignment?\n\nThanks,\n{{recruiter_name}}",
    status: "approved",
    category: "availability",
  },
  {
    name: "Interview confirmation",
    channel: "email",
    subject: "Interview confirmation — {{role_title}}",
    body: "Hi {{first_name}},\n\nYour interview for the {{role_title}} role ({{location}}) is confirmed. You will receive the calendar invitation separately.\n\nPlease have your certificates and ID ready.\n\n{{recruiter_name}}",
    status: "approved",
    category: "pipeline",
  },
  {
    name: "Interview confirmation",
    channel: "whatsapp",
    providerTemplateId: "interview_confirm_v1",
    body: "Hi {{first_name}}, your interview for {{role_title}} ({{location}}) is confirmed. Please have your certificates and ID ready. — {{recruiter_name}}",
    status: "approved",
    category: "pipeline",
  },
  {
    name: "Placement welcome",
    channel: "email",
    subject: "Welcome aboard — {{role_title}}",
    body: "Hi {{first_name}},\n\nCongratulations on your placement as {{role_title}} in {{location}}. Your start date is {{start_date}}. We will send travel and onboarding details shortly.\n\n{{recruiter_name}}",
    status: "approved",
    category: "placement",
  },
  {
    name: "Document request",
    channel: "whatsapp",
    body: "Hi {{first_name}}, to complete your file for {{role_title}} we still need a copy of your certificates. Could you send them here?",
    status: "draft",
    category: "compliance",
  },
  {
    name: "Offer summary",
    channel: "email",
    subject: "Offer summary — {{role_title}}",
    body: "Hi {{first_name}},\n\nPlease find attached the offer summary for {{role_title}} in {{location}}. Let us know if you have questions before signing.\n\n{{recruiter_name}}",
    status: "draft",
    category: "pipeline",
  },
];

export const AUTOMATION_RULES: {
  name: string;
  description: string;
  trigger: "submission_stage_changed" | "placement_status_changed" | "message_failed" | "task_overdue" | "candidate_created" | "requisition_created" | "verification_changed" | "schedule_daily";
  conditions: { field: string; operator: "equals" | "not_equals" | "gte" | "lte" | "in"; value: string | number | boolean | string[] }[];
  action: "create_task" | "notify_owner" | "queue_message" | "update_candidate_status";
  actionConfig: { taskType?: string; title?: string; dueInHours?: number; priority?: "low" | "medium" | "high" | "urgent"; templateName?: string; candidateStatus?: string; notificationTitle?: string };
  isActive: boolean;
  isSystem: boolean;
}[] = [
  {
    name: "Interested → confirm availability",
    description: "When a candidate confirms interest, the owner gets a task to re-confirm dated availability before screening.",
    trigger: "submission_stage_changed",
    conditions: [{ field: "toStage", operator: "equals", value: "interested" }],
    action: "create_task",
    actionConfig: { taskType: "availability_check", title: "Re-confirm availability with {{label}}", dueInHours: 48, priority: "medium" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "Offer made → notify owner",
    description: "Owner is notified the moment an offer is recorded so acceptance can be chased within 48 hours.",
    trigger: "submission_stage_changed",
    conditions: [{ field: "toStage", operator: "equals", value: "offered" }],
    action: "notify_owner",
    actionConfig: { notificationTitle: "Offer recorded for {{label}} — chase acceptance" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "Customer rejection → capture feedback",
    description: "Every customer rejection creates a follow-up task so the structured reason is confirmed with the contact.",
    trigger: "submission_stage_changed",
    conditions: [{ field: "toStage", operator: "equals", value: "rejected_by_customer" }],
    action: "create_task",
    actionConfig: { taskType: "follow_up", title: "Collect customer feedback on {{label}}", dueInHours: 72, priority: "low" },
    isActive: true,
    isSystem: false,
  },
  {
    name: "Placement started → onboarding checklist",
    description: "Starting a placement opens a checklist task for contract, work authorisation and travel evidence.",
    trigger: "placement_status_changed",
    conditions: [{ field: "toStatus", operator: "equals", value: "started" }],
    action: "create_task",
    actionConfig: { taskType: "placement_checklist", title: "Complete onboarding checklist for {{label}}", dueInHours: 120, priority: "high" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "New candidate without contact permission",
    description: "Candidates created without permission to communicate get a manual-contact task so permission is obtained through an allowed channel.",
    trigger: "candidate_created",
    conditions: [{ field: "hasCommunicationConsent", operator: "equals", value: false }],
    action: "create_task",
    actionConfig: { taskType: "manual_contact", title: "Obtain permission to contact {{label}}", dueInHours: 72, priority: "medium" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "Evidence rejected → notify owner",
    description: "When a reviewer rejects evidence, the candidate owner is notified to collect better documentation.",
    trigger: "verification_changed",
    conditions: [{ field: "decision", operator: "equals", value: "rejected" }],
    action: "notify_owner",
    actionConfig: { notificationTitle: "Evidence rejected for {{skill}} — {{label}}" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "Urgent requisition → kick-off sourcing",
    description: "Urgent requests create an immediate sourcing task for the owner.",
    trigger: "requisition_created",
    conditions: [{ field: "priority", operator: "equals", value: "urgent" }],
    action: "create_task",
    actionConfig: { taskType: "follow_up", title: "Kick off sourcing for urgent request: {{label}}", dueInHours: 24, priority: "urgent" },
    isActive: true,
    isSystem: false,
  },
  {
    name: "Message failed → notify owner",
    description: "A failed outreach message notifies the candidate owner in addition to the fallback task.",
    trigger: "message_failed",
    conditions: [],
    action: "notify_owner",
    actionConfig: { notificationTitle: "Outreach to {{label}} failed on {{channel}}" },
    isActive: true,
    isSystem: true,
  },
  {
    name: "Interested → send availability reconfirmation",
    description: "Disabled for the pilot: would queue an availability message on every interest confirmation. Enable once WhatsApp templates are approved.",
    trigger: "submission_stage_changed",
    conditions: [{ field: "toStage", operator: "equals", value: "interested" }],
    action: "queue_message",
    actionConfig: { templateName: "Availability reconfirmation" },
    isActive: false,
    isSystem: false,
  },
];

export const MANUAL_TASKS: { title: string; description?: string; type: "follow_up" | "verification" | "availability_check" | "eligibility_review" | "message_failed" | "stalled_request" | "manual_contact" | "placement_checklist" | "import_review" | "other"; priority: "low" | "medium" | "high" | "urgent"; dueInDays: number; owner: UserKey; candidate?: string; requisition?: string; account?: AccountKey; status?: "open" | "in_progress" | "done" | "cancelled" }[] = [
  { title: "Review BOSIET certificate for Omer Dahan", description: "Scanned OPITO certificate is on the profile. Confirm issue date and mark verified or rejected.", type: "verification", priority: "high", dueInDays: -1, owner: "daniel", candidate: "omer_dahan" },
  { title: "Review armed security licence for Alexey Petrov", description: "Licence photo uploaded; check validity and issuing authority.", type: "verification", priority: "high", dueInDays: 1, owner: "daniel", candidate: "alexey_petrov" },
  { title: "Possible duplicate: Amir Levy (job fair) vs Amir Levi", description: "Same phone number registered at the job fair. Review and merge into the existing profile.", type: "other", priority: "medium", dueInDays: 1, owner: "maya", candidate: "amir_levy_dup" },
  { title: "Chase German permit renewal for Sergei Volkov", description: "Permit from the spring campaign expired. Ask the customer's HR partner whether a renewal can be sponsored.", type: "follow_up", priority: "medium", dueInDays: -2, owner: "daniel", candidate: "sergei_volkov", requisition: "r1_pipe_welders" },
  { title: "Book GWO refresher for Piotr Zieliński", description: "GWO BST expires in about three months; refresher must be complete before Gdańsk mobilisation.", type: "verification", priority: "medium", dueInDays: 14, owner: "yossi", candidate: "piotr_zielinski", requisition: "r6_wind_technicians" },
  { title: "Send framework agreement to Helios Solar", description: "Eleni Georgiou asked for our standard framework and rate card.", type: "follow_up", priority: "high", dueInDays: 0, owner: "yossi", account: "helios", requisition: "r5_pv_electricians" },
  { title: "Confirm turbine delivery date with Baltic Windworks", description: "Requisition on hold until Marek confirms delivery; check every Friday.", type: "stalled_request", priority: "low", dueInDays: 3, owner: "yossi", account: "baltic", requisition: "r6_wind_technicians" },
  { title: "Collect 30-day check-in from Lior Biton", description: "Placement passed probation checkpoint 1; record feedback from Ronit Shaked.", type: "placement_checklist", priority: "medium", dueInDays: 2, owner: "maya", candidate: "lior_biton" },
  { title: "Re-confirm availability: Ruslan Koval", description: "Available from next week per intake; confirm before adding to Helios shortlist.", type: "availability_check", priority: "low", dueInDays: 4, owner: "daniel", candidate: "ruslan_koval" },
  { title: "Reference check for Yuval Stern", description: "Two references received; call both before re-presenting to another customer.", type: "follow_up", priority: "low", dueInDays: -4, owner: "yossi", candidate: "yuval_stern", status: "done" },
  { title: "Prepare weekly pipeline summary for Nordsee Werft", description: "Katrin expects the shortlist update every Monday.", type: "follow_up", priority: "medium", dueInDays: 1, owner: "yossi", account: "nordsee", requisition: "r1_pipe_welders", status: "in_progress" },
];

export const SAVED_FILTERS: { user: UserKey; entity: string; name: string; filters: Record<string, string>; isDefault?: boolean }[] = [
  { user: "maya", entity: "candidates", name: "Welders ready to go", filters: { q: "weld", status: "active" } },
  { user: "maya", entity: "submissions", name: "Needs eligibility review", filters: { eligibility: "review" }, isDefault: true },
  { user: "daniel", entity: "candidates", name: "Pending verification", filters: { verification: "pending_review" }, isDefault: true },
  { user: "yossi", entity: "requisitions", name: "Open European requests", filters: { status: "open" }, isDefault: true },
  { user: "yossi", entity: "placements", name: "Starting this month", filters: { status: "reserved" } },
  { user: "noa", entity: "submissions", name: "Overdue for a stage change", filters: { stalled: "1" } },
];

export const IMPORT_CSV = [
  "First name,Last name,Email,Phone,City,Country,Citizenships,Headline,Military role,Years experience,Skills,Languages,Available from,Expected pay,Currency,Pay period,Willing to relocate",
  "Boris,Kaplan,boris.kaplan@example.com,+972 52 771 9080,Karmiel,IL,IL;RU,Crane operator and rigger,Combat engineer,9,crane operator;heavy equipment operator;forklift,he:fluent;ru:native;en:basic,2026-11-01,32,EUR,hourly,yes",
  "Sergei,Volkov,sergei.volkov@example.com,+972 50 818 4412,Nof HaGalil,IL,IL,Master welder,,15,tig;arc welding,ru:native;he:professional,2026-10-01,36,EUR,hourly,yes",
  "Miriam,Abitbol,miriam.abitbol@example.com,+972 54 302 6611,Netivot,IL,IL,Warehouse supervisor,Logistics NCO,7,warehouse;forklift;dispatch,he:native;en:conversational;fr:fluent,2026-10-15,13500,ILS,monthly,no",
  "Ahmad,Khoury,ahmad.khoury@example.com,+972 52 640 2210,Nazareth,IL,IL,Industrial electrician,,11,electrician;plc;high voltage,ar:native;he:fluent;en:professional,2026-10-20,29,EUR,hourly,yes",
  "Elena,Marinescu,elena.marinescu@example.com,+40 722 118 905,Constanța,Romania,RO,Paramedic,,8,paramedic;first aid,ro:native;en:professional,2026-11-10,4200,EUR,monthly,yes",
].join("\n");
